### ISSUE TITLE
Error when tried to import generate_forecasting_h5

### ISSUE THREAD

**Issue by zyandtom** [argoai/argoverse-api#239]
```
from argoverse.evaluation.competition_util import generate_forecasting_h5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yang.zeng/argoverse-api/argoverse/evaluation/competition_util.py", line 13, in <module>
    import quaternion
ModuleNotFoundError: No module named 'quaternion'
```
when I have installed quaternion, another error emerged, about numpy crash:
```
from argoverse.evaluation.competition_util import generate_forecasting_h5
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yang.zeng/argoverse-api/argoverse/evaluation/competition_util.py", line 13, in <module>
    import quaternion
  File "/home/yang.zeng/.conda/envs/torch/lib/python3.7/site-packages/quaternion/__init__.py", line 25, in <module>
    from .numpy_quaternion import (
ImportError: numpy.core.multiarray failed to import
```
I know it is not compatible for numpy, so I installed numpy=1.19, but still the same error, why?

**Comment by johnwlambert** [comment]
Hi @zyandtom, thanks for the heads up.

Looks like we forget to remove `quaternion` from this file. You won't need it for the forecasting file generation, so please comment out the `import quaternion` for now and `pip uninstall quaternion`, and I'll put up a PR ASAP to refactor this file and remove that dependency.

Thanks.

**Comment by johnwlambert** [comment]
This issue should be resolved by https://github.com/argoai/argoverse-api/pull/249
