### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by leafstar** [argoai/argoverse-api#338]
When I run "pip install -e .", I have the following issue:

Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      /private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py", line 235, in <module>
          main()
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-install-_w1uj5gm/numpy_a3c67b829075409584a1ca25e25cc983/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/Users/muxingwang/anaconda3/envs/HiVT/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/muxingwang/anaconda3/envs/HiVT/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/muxingwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/muxingwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/muxingwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-build-env-6_mkb4te/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-build-env-6_mkb4te/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/l8/nqhf7dw1551fb5gmjp3d0kmm0000gn/T/pip-build-env-6_mkb4te/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 274, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cchingyii** [comment]
hi，bro，how do you slave with the promblem？

**Comment by ConnerLusk** [comment]
Bumping numpy to 1.21 fixed this issue for me
